.TH detect_obj_free 3 2019-08-01 "libchardet manuals"
.\" Process with
.\" nroff -man detect_obj_free.3
.\" 2019-08-01 JoungKyun Kim <htt://oops.org>

.SH NAME
chardet_obj_free - free DetectObject structure

.SH SNOPSIS
.I #include <chardet.h>
.br
.I void chardet_obj_free (DetectObj **);

.SH DESCRIPTION
Free resource of DetectObject structure that allocated by
.B chardet_obj_init
api

.SH "RETURN VALUE"
void
.PP

.SH EXAMPLE
.nf
#include <chardet.h>

int main (void) {
	DetectObj *obj;

	if ( (obj = detect_obj_init ()) == NULL ) {
		fprintf (stderr, "Memory Allocation failed\\n");
		return CHARDET_MEM_ALLOCATED_FAIL;
	}

	switch (detect ("¾È³çÇÏ¼¼¿ä", &obj)) {
		case CHARDET_OUT_OF_MEMORY :
			fprintf (stderr, "On handle processing, occured out of memory\\n");
			detect_obj_free (&obj);
			return CHARDET_OUT_OF_MEMORY;
		case CHARDET_NULL_OBJECT :
			fprintf (stderr,
					"2st argument of chardet() is must memory allocation "
					"with detect_obj_init API\\n");
			return CHARDET_NULL_OBJECT;
	}

	# check support obj->bom with CHARDET_BOM_CHECK constant
	printf ("encoding: %s, confidence: %f, exists bom: %d\\n", obj->encoding, obj->confidence, obj->bom);
	detect_obj_free (&obj);

    return 0;
}
.fi

.SH AUTHORS
JoungKyun.Kim <http://oops.org>

.SH "BUG REPORTS"
Use QnA board on https://github.com/Joungkyun/libchardet/issues

.SH "SEE ALSO"
detect_obj_init(3)

