#!/bin/sh
#
# $Id$

export LIBTOOL=/usr/bin/libtool
export AUTOMAKE=/usr/bin/automake
export ACLOCAL=/usr/bin/aclocal
rm -f configure tools/{config.guess,config.sub,ltmain.sh}
autoreconf --install
rm -rf autom4te* aclocal.m4

exit 0
